services:
  - type: web
    name: epbot
    buildCommand: cd artifacts/elited-vip && pip install -r requirements.txt
    startCommand: cd artifacts/elited-vip && python main.py
    envVars:
      - key: BOT_TOKEN
      - key: ADMIN_ID
      - key: PORT
        value: 10000
